[package]
name    = "nasadem"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = { workspace = true }
geo       = { workspace = true }
memmap2   = { workspace = true }
thiserror = { workspace = true }
