[package]
name = "zorderize"
version = "0.1.0"
edition = "2021"

[dependencies]
clap    = { workspace = true }
glob    = "0"
image   = { workspace = true }
nasadem = { path = "..", features = ["image"] }
