[package]
name = "terrain"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap   = { workspace = true }
geo       = { workspace = true }
nasadem   = { path = "../nasadem" }
thiserror = { workspace = true }

[dev-dependencies]
plotters  = { workspace = true }
