[package]
name = "terrain"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap   = { workspace = true }
geo       = { workspace = true }
nasadem   = { path = "../nasadem" }
thiserror = { workspace = true }

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
plotters  = { workspace = true }
[target.'cfg(not(target_env = "msvc"))'.dev-dependencies]
tikv-jemallocator = "0.5"

[[bench]]
name = "benchmarks"
harness = false
